### PR TITLE
WIP: Set up JSDoc

### PR DESCRIPTION
**Pull request by tomasleeruniek**
I started working on setting up JSDoc to generate documentation for the library. It works for some functions right now, but not for modules which are anonymous functions (i.e. most of them). ~I'll look into whether it's possible to configure JSDoc to pick up these functions without having to name them in the source file~. You just need to provide `@name` in the doc.

It would also be worthwhile to separate the functions into modules/namespaces, for instance having an Array module that only contains list processing functions.

### CODE REVIEW

**Comment by andreidmt** [comment]
FYI https://www.npmjs.com/package/dox + .ejs templates

**Comment by andreidmt** [comment]
I used `@tag` in some comments as a "namespace"

**Comment by tomasleeruniek** [comment]
> FYI https://www.npmjs.com/package/dox + .ejs templates

I also found https://github.com/documentationjs/documentation which is more recent and appears to be actively maintained. I'll look into both as options.

**Comment by andreidmt** [comment]
`documentationjs` looks better, yeah

**Pull request merged**
